### PR TITLE
[MASTER] Resolved #44

### LINKED ISSUE #44: Must not be able to sucessfully validate a given TOTP twice
## Description

From [RFC 6238](https://tools.ietf.org/html/rfc6238):

> Note that a prover may send the same OTP inside a given time-step
> window multiple times to a verifier.  The verifier MUST NOT accept
> the second attempt of the OTP after the successful validation has
> been issued for the first OTP, which ensures one-time only use of an
> OTP.

Once ROTP successfully verifies a TOPT, it should no longer accept subsequent verifications of the same value.

I couldn't find any reference to this requirement for HOTP in [RFC 4226](https://tools.ietf.org/html/rfc4226). Only TOPT appears to apply. 

## Expected

```ruby
otp = ROTP::TOTP.new("base32secret3232")
value = foo.now
foo.verify(value) #=> true
foo.verify(value) #=> false
foo.verify(value) #=> false
```

## Actual

```ruby
otp = ROTP::TOTP.new("base32secret3232")
value = foo.now
foo.verify(value) #=> true
foo.verify(value) #=> true
foo.verify(value) #=> true
```

## Security Impact

In a two-factor authentication context, an attacker could Man-in-The-Middle the connection between the verifier and provider, obtain the username, password, & OTP values, and log in with the credentials within the current time step (a 30 second window, if defaults are used). Arguably, this defeats the two-factor authentication since the OTP can be replayed multiple times.

Alternatively, an attacker could “shoulder surf” the victim’s second factor device in lieu of compromising the connection.

### PR DESCRIPTION
**Pull request by HugoPouliquen**

### CODE REVIEW

**Comment by mdp** [comment]
Hey Hugo,

First off thanks for taking the time to build this. It a really nice implementation. Few issues on my end.

1. I think we should pull this out into a separate module. Something along the lines of

```ruby
require 'rotp_redis_cache'

ROTP.configure do |config|
 config.last_otp_counter_cache = new ROTPRedisCache({
     config: blah
  })
end
```

2. Rather than keeping track of the OTP's, we could simply keep track of the last 'time interval'(essentially the counter) we successfully verified an OTP. Then you don't need to worry about expiring the OTP's, simply ensure that we are using a 'time interval' greater than the last successful one. So if we're using MySQL, we can simply store the last successful 'time interval' and not worry about how long ago it was used and when to expire it.

Thoughts?

Thanks

**Comment by HugoPouliquen** [comment]
Thanks for replying quickly !

1. Yes it's a good idea. But what is the main aim?
- If you want to have several cache implementation, it's already possible to do that.
ROTP uses the null_cache driver by default. We can configure redis or add another driver on the same redis interface.
- Or maybe you want to externalize the system in a new gem (extension) ? This works for us too.

2. Yes I agree that we can store the timestamp instead of saving the token. But wouldn't it be 
more difficult to manage if we have problems with syncronisation between the server and the client?
We could have a salt token to prevent sensitive information in the database.
If we externalize the system in the new gem, each user will be able to choose the way to store his token.

I will be out of office until next month.

**Comment by mdp** [comment]
Yeah, for 1. I just think this would make a really good external gem that people could add on. The other benefit is that development changes to it would not be tied to new releases of ROTP and it would be a good template for other that wanted to build a mySQL/Postgres/Memcache version.

2. I'm not worried about sensitive information in the database (I don't think your expired 6 digit OTP would be that useful in a db dump). I'm more interested in what information I'd need to store and the complexity. For example, if we store the OTP, we also need to store the expiration date, which is tied to how long the interval is. If we just store the last timestamp used, we only need to ensure that we never use a timestamp less than or equal to the one we stored.

For synchronization with the client, usually clients are off by a small amount of time, which is why ROTP provides a 'drift' function. Even if the client is a little off, it should never go back in time, so I don't think this would introduce any issue, but maybe I'm missing something. The benefit is that this also works with HOTP, where timestamp is just the counter. So now if you have a mySQL store, it works for both TOTP and HOTP.

**Comment by HugoPouliquen** [comment]
The [external gem](https://github.com/PredicSis/rotp-redis/pull/1) is done. Let me know if you have any comments or questions.

**Comment by mdp** [comment]
Closing this in favor of #58

**Pull request closed without merging**
