### PR TITLE
Added simple rtotp binary

### PR DESCRIPTION
**Pull request by halo**
While I understand that this is a pure library, I find myself often just wanting to generate a token from a salt without too much work. Much like [HTTParty](https://github.com/jnunemaker/httparty/blob/master/bin/httparty) I though a small binary to accomplish this might not hurt.

Do you think an executable like this would be useful? I doubt that the *name* of the executalbe is very useful, but it is almost guaranteed to not cause a conflict :)

Thank you for your feedback.

### CODE REVIEW

**Comment by mdp** [comment]
Hey, sorry for not getting back to you on this. I actually think this would be a useful addition as well.

You pull request looks like a great start, but ideally it would allow for both HOTP and TOTP tokens as well as using the Ruby OptionParser for argument parsing and maybe a small but simple test.

Anyways, I'm a bit swamped at the moment, but I'll try and add this in the near future.

Thanks,
Mark

**Comment by halo** [comment]
Thank you for your feedback. I will gladly implement those things. Hang on for an update.

**Comment by halo** [comment]
Would you mind giving me feedback on the look and feel of the output of the executable? Is it intuitive for you so far? Should it also be able to generate URI's? There are still some holes in the spec coverage but you can at least try it out now.

PS: Funny enough, there appears to be more code for the CLI now than for the core functionality ;)

**Comment by mdp** [comment]
Looks really good, I think the coverage is fine for this, as it's not critical to the core product, it's more of a helpful addition for debugging.

I'll do a quick pass tonight and add it to the README and bump the version.

Thanks again

**Comment by halo** [comment]
Awesome! Thank you. I thought I'd get you kickstarted with the README: #37

**Pull request merged**
