### PR TITLE
Readying for v2.1.0

### PR DESCRIPTION
**Pull request by mdp**
Couple of minor changes. @halo can you take a quick look at this and see if it makes sense. If so, I'll merge and release this as v2.1.0. Thanks

### CODE REVIEW

**Comment by mdp** [comment]
Just to be clear about 885c07a since it's buried in that commit, the '0' character is not valid in the Base32 key string.

**Comment by halo** [comment]
Makes perfect sense. Thank you.

(I was just wondering whether the `0` should not have raised some error when used as secret)

**Comment by mdp** [comment]
It does raise a Base32 error. When I tried your sample command it raised an
error about the Base32 charset not including '0'.

Could possibly make it a bit more clear I suppose.

**Comment by halo** [comment]
Ship it :)

**Comment by mdp** [comment]
Thanks for implementing this and updating the project specs. It's live in 2.1.0 - https://rubygems.org/gems/rotp

**Pull request merged**
